pipeline {
    agent devserver
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Starting the Build Process"'
            }
            
        }
        stage('Test') {
            steps {
                sh 'echo test'
            }
            
        }
        stage('Deliver') { 
            steps {
                sh 'echo "Delivering the Application"' 
            }
        }
    }
}
