pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Starting the Build Process"'
            }
            steps {
                #sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                #sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                #sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
